---
- name: Install aptitude
  become: yes
  become_user: root
  apt:
    name: aptitude
    state: present
    update_cache: true

- name: Install required system packages
  become: yes
  become_user: root
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - rsync
      - docker-compose
    state: present
    update_cache: true

- name: Add Docker GPG apt Key
  become: yes
  become_user: root
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: yes
  become_user: root 
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  become: yes
  become_user: root
  apt:
    name: docker-ce
    state: present
    update_cache: true

- name: Install Docker Module for Python
  become: yes
  become_user: root
  pip:
    name: docker

- name: Create the docker group 
  become: yes
  become_user: root
  group:
    name: docker
    state: present

- name: Get the current user
  shell: echo $USER
  register: current_user

- name: Add the current user in docker group
  become: yes
  become_user: root
  user:
    name: "{{ current_user.stdout }}"
    groups: docker
    append: yes
    state: present

- name: Chown the docker socket with ansible user
  become: yes
  become_user: root
  file:
    path: /var/run/docker.sock
    owner: "{{ user_ansible }}"
    group: "{{ user_ansible }}"
    state: file
