---  
- name: Create bind folders for shared volumes
  become: yes
  become_user: root
  file:
    path: "{{ bind_folder }}/{{ item }}"
    owner: "{{ user_ansible }}"
    group: "{{ user_ansible }}"
    state: directory
  with_items:
    - mariadb
    - wordpress
    - adminer